vich_uploader:
    db_driver: orm

    mappings:
       aliment_images:
           uri_prefix: /images/aliments
           upload_destination: '%kernel.project_dir%/public/images/aliments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       type_images:
           uri_prefix: /images/types
           upload_destination: '%kernel.project_dir%/public/images/types'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer    
